<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AvroSourceGeneratorAvroLibrary>Chr</AvroSourceGeneratorAvroLibrary>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Chr.Avro.Confluent" />
    <PackageReference Include="Testcontainers" />
  </ItemGroup>

  <!--Required since we're referencing the generator through the csproj instead of the package -->
  <Import Project="..\..\AvroSourceGenerator.props" />

  <ItemGroup>
    <AdditionalFiles Include="*.avsc" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\AvroSourceGenerator\AvroSourceGenerator.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
  </ItemGroup>

</Project>
