using System.Reflection;

namespace AvroSourceGenerator;

internal partial class AvroSourceGenerator
{
    public const string AutoGeneratedComment = """
        //------------------------------------------------------------------------------
        // <auto-generated>
        //     This code was generated by a tool.
        //
        //     Changes to this file may cause incorrect behavior and will be lost if
        //     the code is regenerated.
        // </auto-generated>
        //------------------------------------------------------------------------------
        """;

    public static AssemblyName AssemblyName { get; } = typeof(AvroSourceGenerator).Assembly.GetName();
    public static string GeneratedCodeAttribute { get; } = $@"global::System.CodeDom.Compiler.GeneratedCodeAttribute(""{AssemblyName.Name}"", ""{AssemblyName.Version}"")";
    private static readonly string AvroModelAttribute = $$$"""
        {{{AutoGeneratedComment}}}
        namespace AvroSourceGenerator
        {
            [{{{GeneratedCodeAttribute}}}]
            [global::System.AttributeUsage(global::System.AttributeTargets.Class, AllowMultiple = false)]
            internal sealed class AvroModelAttribute : global::System.Attribute
            {
                public AvroModelFeatures Features { get; }

                public AvroModelAttribute(AvroModelFeatures features)
                {
                    Features = features;
                }
            }

            [global::System.Flags]
            internal enum AvroModelFeatures
            {
                None = 0,
                NullableReferenceTypes = 1 << 0,
                FileScopedNamespaces = 1 << 1,
                InitOnlyProperties = 1 << 2,
                RequiredProperties = 1 << 3,
                UnsafeAccessors = 1 << 4,

                NetStandard2_0 = None,
                Net472 = None,
                Net48 = None,
                NetStandard2_1 = NullableReferenceTypes,
                Net5 = NullableReferenceTypes | FileScopedNamespaces,
                Net6 = NullableReferenceTypes | FileScopedNamespaces | InitOnlyProperties,
                Net7 = NullableReferenceTypes | FileScopedNamespaces | InitOnlyProperties | RequiredProperties,
                Net8 = NullableReferenceTypes | FileScopedNamespaces | InitOnlyProperties | RequiredProperties | UnsafeAccessors,
            }
        }
        """;

    public const string AvroSchemaTypeName = "global::Avro.Schema";
    public const string AvroFixedSchemaTypeName = "global::Avro.FixedSchema";
    public const string AvroISpecificRecordTypeName = "global::Avro.Specific.ISpecificRecord";
    public const string AvroSpecificExceptionTypeName = "global::Avro.Specific.SpecificException";
    public const string AvroSpecificFixedTypeName = "global::Avro.Specific.SpecificFixed";
    public const string AvroGenericFixedTypeName = "global::Avro.Generic.GenericFixed";
}
