<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <ConsumerLibrary>Apache</ConsumerLibrary>
    <DefineConstants>$(DefineConstants);APACHE</DefineConstants>
  </PropertyGroup>
  <Import Project="../Consumer.targets" />
  <ItemGroup>
    <PackageReference Include="Apache.Avro" />
  </ItemGroup>
</Project>
