<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <UseMicrosoftTestingPlatformRunner>true</UseMicrosoftTestingPlatformRunner>
    <AvroSourceGeneratorPreviewFeatures>None</AvroSourceGeneratorPreviewFeatures>
    <AvroSourceGeneratorAvroLibrary>Chr</AvroSourceGeneratorAvroLibrary>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="xunit.runner.json" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Chr.Avro.Binary" />
    <PackageReference Include="Chr.Avro.Codegen" />
    <PackageReference Include="Chr.Avro.Json" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="Microsoft.Testing.Extensions.GitHubActionsReport" PrivateAssets="all" />
    <PackageReference Include="xunit.v3" />
    <PackageReference Include="xunit.runner.visualstudio">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\AvroSourceGenerator\AvroSourceGenerator.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
    <ProjectReference Include="..\AvroSourceGenerator.IntegrationTests\AvroSourceGenerator.IntegrationTests.csproj" />
  </ItemGroup>

  <Import Project="..\..\AvroSourceGenerator.props" />

  <ItemGroup>
    <AdditionalFiles Include="..\Schemas\*.avdl" CopyToOutputDirectory="PreserveNewest" Link="Schemas\%(Filename)%(Extension)" />
    <AdditionalFiles Include="..\Schemas\*.avsc" CopyToOutputDirectory="PreserveNewest" Link="Schemas\%(Filename)%(Extension)" />
    <AdditionalFiles Include="..\Schemas\*.avpr" CopyToOutputDirectory="PreserveNewest" Link="Schemas\%(Filename)%(Extension)" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="..\Serialization\Common\**\*.cs" Exclude="..\Serialization\Common\**\*SmokeTests.cs;..\Serialization\Common\**\*ModelTests.cs" Link="Serialization\%(Filename)%(Extension)" />
    <Compile Include="..\Serialization\Chr\**\*.cs" Link="Serialization\%(Filename)%(Extension)" />
    <Compile Include="..\Serialization\ChrObjectUnions\**\*.cs" Link="Serialization\%(Filename)%(Extension)" />
    <Compile Include="..\Serialization\ObjectUnions\**\*.cs" Link="Serialization\%(Filename)%(Extension)" />
  </ItemGroup>

</Project>
