using Xunit;

namespace AvroSourceGenerator.Tests;

public class AvroSchemaGeneratorUnitTests
{
    private readonly string _source = $$""""
        using System;
        using AvroSourceGenerator;

        namespace AvroSourceGenerator.Tests;

        [Avro({{nameof(LanguageFeatures)}}.{{TestHelpers.LanguageFeatures}})]
        public partial record class User
        {
            public const string AvroSchema = """
            {
                "type": "record",
                "namespace": "Tests.User",
                "name": "User",
                "fields" : [
                    { "name": "Name", "type": "string" },
                    { "name": "Age", "type": "int", "default": 18 },
                    { "name": "Description", "type": [ "string", "null" ] }
                ]
            }
            """;
        }
        """";

    [Fact]
    public void Generator_WithCandidates_AddRecord()
    {
        const string ExpectedContent = """"
            // <auto-generated/>
            #pragma warning disable
            #nullable enable
            namespace AvroSourceGenerator.Tests;

            [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("AvroSourceGenerator", "1.0.0.0")]
            public partial record class User : global::Avro.Specific.ISpecificRecord
            {
                public static readonly global::Avro.Schema _SCHEMA = global::Avro.Schema.Parse(AvroSchema);
                public global::Avro.Schema Schema { get => User._SCHEMA; }
                public required string Name { get; init; }
                public required int Age { get; init; } = 18;
                public string? Description { get; init; }
                public object? Get(int fieldPos)
                {
                    switch (fieldPos)
                    {
                        case 0: return this.Name;
                        case 1: return this.Age;
                        case 2: return this.Description;
                        default: throw new global::Avro.AvroRuntimeException($"Bad index {fieldPos} in Get()");
                    }
                }
                public void Put(int fieldPos, object? fieldValue)
                {
                    switch (fieldPos)
                    {
                        case 0: Set_Name(this, (string)fieldValue!); break;
                        case 1: Set_Age(this, (int)fieldValue!); break;
                        case 2: Set_Description(this, (string?)fieldValue!); break;
                        default: throw new global::Avro.AvroRuntimeException($"Bad index {fieldPos} in Put()");
                    }
                    [global::System.Runtime.CompilerServices.UnsafeAccessor(global::System.Runtime.CompilerServices.UnsafeAccessorKind.Method, Name = "set_Name")]
                    extern static void Set_Name(User obj, string value);
                    [global::System.Runtime.CompilerServices.UnsafeAccessor(global::System.Runtime.CompilerServices.UnsafeAccessorKind.Method, Name = "set_Age")]
                    extern static void Set_Age(User obj, int value);
                    [global::System.Runtime.CompilerServices.UnsafeAccessor(global::System.Runtime.CompilerServices.UnsafeAccessorKind.Method, Name = "set_Description")]
                    extern static void Set_Description(User obj, string? value);
                }
            }

            #nullable restore
            #pragma warning restore
            
            """";

        TestHelpers.Verify(_source,
            new Document("User.Avro.g.cs", ExpectedContent));
    }
}
