<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsPackable>true</IsPackable>
    <IncludeBuildOutput>false</IncludeBuildOutput>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
    <NoWarn>$(NoWarn);NU5128</NoWarn>
  </PropertyGroup>

  <PropertyGroup>
    <PackageId>AvroSourceGenerator</PackageId>
    <Title>Avro Source Generator</Title>
    <Authors>sadicangel</Authors>
    <Company>sadicangel</Company>
    <Description>A source generator that generates C# code from Avro schema, protocol, and IDL files and is compatible with Apache Avro.</Description>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageTags>apache;avro;apache-avro;source-generator;codegen;csharp;c#;net;dotnet;schema;protocol;serialization;avsc;avpr;avdl;idl;avro-idl;models</PackageTags>
    <RepositoryUrl>https://github.com/sadicangel/avro-source-generator</RepositoryUrl>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageIcon>icon.png</PackageIcon>
  </PropertyGroup>

  <ItemGroup>
    <None Include="../../README.md" Pack="true" PackagePath="/" />
    <None Include="../../icon.png" Pack="true" PackagePath="/" />
    <None Include="../../AvroSourceGenerator.props" Pack="true" PackagePath="build" Visible="false" />
    <ProjectReference Include="../AvroSourceGenerator/AvroSourceGenerator.csproj" ReferenceOutputAssembly="false" PrivateAssets="all" />
    <ProjectReference Include="../AvroSourceGenerator.Roslyn5_0/AvroSourceGenerator.Roslyn5_0.csproj" ReferenceOutputAssembly="false" PrivateAssets="all" />
  </ItemGroup>

  <Target Name="CollectGeneratorPackageFiles" BeforeTargets="_GetPackageFiles">
    <MSBuild Projects="@(ProjectReference)" Targets="GetGeneratorPackageFiles" Properties="Configuration=$(Configuration)">
      <Output TaskParameter="TargetOutputs" ItemName="_GeneratorPackageFiles" />
    </MSBuild>
    <ItemGroup>
      <None Include="@(_GeneratorPackageFiles)" />
    </ItemGroup>
  </Target>
</Project>
