using System.Reflection;

namespace AvroNet;

internal partial class AvroGenerator
{
    public const string TabString = "    ";
    public const string AutoGeneratedComment = """
        //------------------------------------------------------------------------------
        // <auto-generated>
        //     This code was generated by a tool.
        //
        //     Changes to this file may cause incorrect behavior and will be lost if
        //     the code is regenerated.
        // </auto-generated>
        //------------------------------------------------------------------------------
        """;

    public static AssemblyName AssemblyName { get; } = typeof(AvroGenerator).Assembly.GetName();
    public static string GeneratedCodeAttribute { get; } = $@"global::System.CodeDom.Compiler.GeneratedCodeAttribute(""{AssemblyName.Name}"", ""{AssemblyName.Version}"")";
    private static readonly string AvroModelAttribute = $$"""
        {{AutoGeneratedComment}}
        namespace AvroNet
        {
            [{{GeneratedCodeAttribute}}]
            [global::System.AttributeUsage(global::System.AttributeTargets.Class, AllowMultiple = false)]
            internal sealed class AvroModelAttribute : global::System.Attribute { }
        }
        """;

    public const string AvroSchemaTypeName = "global::Avro.Schema";
    public const string AvroFixedSchemaTypeName = "global::Avro.FixedSchema";
    public const string AvroISpecificRecordTypeName = "global::Avro.Specific.ISpecificRecord";
    public const string AvroSpecificExceptionTypeName = "global::Avro.Specific.SpecificException";
    public const string AvroSpecificFixedTypeName = "global::Avro.Specific.SpecificFixed";
    public const string AvroGenericFixedTypeName = "global::Avro.Generic.GenericFixed";
}
