using Avro;
using Avro.Generic;
using Avro.Specific;
using System.Reflection;

namespace AvroNet;

internal partial class AvroGenerator
{
    public const string TabString = "    ";
    public const string AutoGeneratedComment = """
        //------------------------------------------------------------------------------
        // <auto-generated>
        //     This code was generated by a tool.
        //
        //     Changes to this file may cause incorrect behavior and will be lost if
        //     the code is regenerated.
        // </auto-generated>
        //------------------------------------------------------------------------------
        """;

    public static AssemblyName AssemblyName { get; } = typeof(AvroGenerator).Assembly.GetName();
    public static string GeneratedCodeAttribute { get; } = $@"global::System.CodeDom.Compiler.GeneratedCodeAttribute(""{AssemblyName.Name}"", ""{AssemblyName.Version}"")";
    private static readonly string AvroModelAttribute = $$"""
        {{AutoGeneratedComment}}
        #nullable enable
        namespace AvroNet;

        [{{GeneratedCodeAttribute}}]
        [global::System.AttributeUsage(global::System.AttributeTargets.Class, AllowMultiple = false)]
        internal sealed class AvroModelAttribute : global::System.Attribute
        {
        #if NET8_0_OR_GREATER
            private const int NET = 8;
        #elif NET7_0_OR_GREATER
            private const int NET = 7;
        #elif NET6_0_OR_GREATER
            private const int NET = 6;
        #elif NET5_0_OR_GREATER
            private const int NET = 5;
        #else
            private const int NET = 2;
        #endif
        }
        #nullable restore
        """;
    public static readonly string AvroSchemaTypeName = $"global::{typeof(Schema).FullName}";
    public static readonly string AvroFixedSchemaTypeName = $"global::{typeof(FixedSchema).FullName}";
    public static readonly string AvroISpecificRecordTypeName = $"global::{typeof(ISpecificRecord).FullName}";
    public static readonly string AvroSpecificExceptionTypeName = $"global::{typeof(SpecificException).FullName}";
    public static readonly string AvroSpecificFixedTypeName = $"global::{typeof(SpecificFixed).FullName}";
    public static readonly string AvroGenericFixedTypeName = $"global::{typeof(GenericFixed).FullName}";
}
