namespace AvroSourceGenerator.Diagnostics;

public static class MessageTemplate
{
    public const string None = "No diagnostic.";
    public const string UnsupportedSourceType = "Unsupported Avro source file type.";
    public const string EmptySource = "Source file is empty.";
    public const string DuplicateSourcePath = "Source path '{0}' duplicates '{1}' after canonicalization.";
    public const string DuplicateSchema = "The type '{0}' is declared more than once.";
    public const string MissingReferences = "The schema reference(s) '{0}' could not be resolved.";
    public const string InvalidJson = "Invalid JSON: {0}";
    public const string EmptyJson = "JSON value expected.";
    public const string TrailingJsonContent = "Additional text encountered after the JSON value.";
    public const string SchemaExpected = "An Avro schema is expected.";
    public const string ProtocolExpected = "An Avro protocol is expected.";
    public const string MissingRootSchema = "A named schema or protocol is required.";
    public const string InvalidSchemaValue = "Invalid Avro schema value '{0}'.";
    public const string ObjectExpected = "An object is required, but '{0}' was found.";
    public const string MissingSchemaProperty = "Required property '{0}' is missing.";
    public const string InvalidStringProperty = "Property '{0}' must be {1}, but '{2}' was found.";
    public const string InvalidArrayProperty = "Property '{0}' must be an array, but '{1}' was found.";
    public const string InvalidObjectProperty = "Property '{0}' must be an object, but '{1}' was found.";
    public const string InvalidBooleanProperty = "Property '{0}' must be a boolean, but '{1}' was found.";
    public const string InvalidStringArrayElement = "Property '{0}' must be an array of non-empty strings.";
    public const string InvalidFixedSize = "Property 'size' must be a positive integer, but '{0}' was found.";
    public const string InvalidAvroName = "'{0}' is not a valid Avro name.";
    public const string UnknownSchemaType = "Unknown Avro schema type '{0}'.";
    public const string RecursiveSchemaDefinition = "Recursive schema definition detected for '{0}'.";
    public const string InvalidOneWayMessage = "One-way message '{0}' must have a null response and no errors.";
    public const string InvalidCharacter = "Invalid character '{0}'.";
    public const string InvalidEscapeSequence = "Invalid escape sequence '{0}'.";
    public const string InvalidNumber = "Invalid number literal '{0}'.";
    public const string UnterminatedDocumentation = "Unterminated documentation comment.";
    public const string UnterminatedComment = "Unterminated comment.";
    public const string UnterminatedString = "Unterminated string literal.";
    public const string UnterminatedVerbatimIdentifier = "Unterminated verbatim identifier.";
    public const string UnexpectedToken = "Unexpected token '{0}'; expected '{1}'.";
    public const string UnexpectedJsonValue = "Unexpected JSON value token '{0}'.";
    public const string MisplacedAnnotation = "Annotation '@{0}' is not valid on {1}.";
    public const string MisplacedDocumentation = "Documentation comment is not valid on {0}.";
    public const string InvalidIdlDocument = "An Avro IDL file must contain a main schema directive or a single protocol declaration.";
    public const string InvalidIdlDeclaration = "Invalid Avro IDL declaration '{0}'.";
    public const string InvalidIdlType = "Invalid Avro IDL type '{0}'.";
    public const string InvalidIdlSchemaDeclaration = "Invalid Avro IDL schema declaration '{0}'.";
    public const string InvalidIdlPrimitive = "Invalid Avro IDL primitive type '{0}'.";
    public const string InvalidIdlFixedSize = "Fixed size must be a positive integer.";
    public const string InvalidIdlDecimalPrecision = "Decimal precision must be an integer.";
    public const string InvalidIdlDecimalScale = "Decimal scale must be an integer.";
    public const string InvalidIdlLogicalType = "Invalid Avro IDL logical type '{0}'.";
    public const string ImportCycle = "Import cycle detected: {0}.";
    public const string InvalidImportFileExtension = "Import kind '{0}' requires a '{1}' target, but '{2}' was specified.";
    public const string MissingImport = "Import path '{0}' does not match an Avro AdditionalFile.";
    public const string InvalidImportTarget = "Import path '{0}' is not a valid {1} target.";
    public const string NoAvroLibraryDetected = "AvroLibrary is set to 'Auto', but no supported Avro library was found.";
    public const string MultipleAvroLibrariesDetected = "Multiple Avro libraries are referenced: {0}. Set AvroSourceGeneratorAvroLibrary to one of: {1}.";

    public static string Get(AvroDiagnosticCode code) => code switch
    {
        AvroDiagnosticCode.None => None,
        AvroDiagnosticCode.UnsupportedSourceType => UnsupportedSourceType,
        AvroDiagnosticCode.EmptySource => EmptySource,
        AvroDiagnosticCode.DuplicateSourcePath => DuplicateSourcePath,
        AvroDiagnosticCode.DuplicateSchema => DuplicateSchema,
        AvroDiagnosticCode.MissingReferences => MissingReferences,
        AvroDiagnosticCode.InvalidJson => InvalidJson,
        AvroDiagnosticCode.EmptyJson => EmptyJson,
        AvroDiagnosticCode.TrailingJsonContent => TrailingJsonContent,
        AvroDiagnosticCode.SchemaExpected => SchemaExpected,
        AvroDiagnosticCode.ProtocolExpected => ProtocolExpected,
        AvroDiagnosticCode.MissingRootSchema => MissingRootSchema,
        AvroDiagnosticCode.InvalidSchemaValue => InvalidSchemaValue,
        AvroDiagnosticCode.ObjectExpected => ObjectExpected,
        AvroDiagnosticCode.MissingSchemaProperty => MissingSchemaProperty,
        AvroDiagnosticCode.InvalidStringProperty => InvalidStringProperty,
        AvroDiagnosticCode.InvalidArrayProperty => InvalidArrayProperty,
        AvroDiagnosticCode.InvalidObjectProperty => InvalidObjectProperty,
        AvroDiagnosticCode.InvalidBooleanProperty => InvalidBooleanProperty,
        AvroDiagnosticCode.InvalidStringArrayElement => InvalidStringArrayElement,
        AvroDiagnosticCode.InvalidFixedSize => InvalidFixedSize,
        AvroDiagnosticCode.InvalidAvroName => InvalidAvroName,
        AvroDiagnosticCode.UnknownSchemaType => UnknownSchemaType,
        AvroDiagnosticCode.RecursiveSchemaDefinition => RecursiveSchemaDefinition,
        AvroDiagnosticCode.InvalidOneWayMessage => InvalidOneWayMessage,
        AvroDiagnosticCode.InvalidCharacter => InvalidCharacter,
        AvroDiagnosticCode.InvalidEscapeSequence => InvalidEscapeSequence,
        AvroDiagnosticCode.InvalidNumber => InvalidNumber,
        AvroDiagnosticCode.UnterminatedDocumentation => UnterminatedDocumentation,
        AvroDiagnosticCode.UnterminatedComment => UnterminatedComment,
        AvroDiagnosticCode.UnterminatedString => UnterminatedString,
        AvroDiagnosticCode.UnterminatedVerbatimIdentifier => UnterminatedVerbatimIdentifier,
        AvroDiagnosticCode.UnexpectedToken => UnexpectedToken,
        AvroDiagnosticCode.UnexpectedJsonValue => UnexpectedJsonValue,
        AvroDiagnosticCode.MisplacedAnnotation => MisplacedAnnotation,
        AvroDiagnosticCode.MisplacedDocumentation => MisplacedDocumentation,
        AvroDiagnosticCode.InvalidIdlDocument => InvalidIdlDocument,
        AvroDiagnosticCode.InvalidIdlDeclaration => InvalidIdlDeclaration,
        AvroDiagnosticCode.InvalidIdlType => InvalidIdlType,
        AvroDiagnosticCode.InvalidIdlSchemaDeclaration => InvalidIdlSchemaDeclaration,
        AvroDiagnosticCode.InvalidIdlPrimitive => InvalidIdlPrimitive,
        AvroDiagnosticCode.InvalidIdlFixedSize => InvalidIdlFixedSize,
        AvroDiagnosticCode.InvalidIdlDecimalPrecision => InvalidIdlDecimalPrecision,
        AvroDiagnosticCode.InvalidIdlDecimalScale => InvalidIdlDecimalScale,
        AvroDiagnosticCode.InvalidIdlLogicalType => InvalidIdlLogicalType,
        AvroDiagnosticCode.InvalidIdlOneWayMessage => InvalidOneWayMessage,
        AvroDiagnosticCode.ImportCycle => ImportCycle,
        AvroDiagnosticCode.InvalidImportFileExtension => InvalidImportFileExtension,
        AvroDiagnosticCode.MissingImport => MissingImport,
        AvroDiagnosticCode.InvalidImportTarget => InvalidImportTarget,
        AvroDiagnosticCode.NoAvroLibraryDetected => NoAvroLibraryDetected,
        AvroDiagnosticCode.MultipleAvroLibrariesDetected => MultipleAvroLibrariesDetected,
        _ => throw new ArgumentOutOfRangeException(nameof(code), code, null)
    };
}
