namespace AvroSourceGenerator.Diagnostics;

public static class MessageTemplate
{
    public const string None = "No diagnostic";
    public const string UnsupportedSourceType = "Unsupported Avro source file type; expected .avsc, .avpr, or .avdl";
    public const string EmptySource = "Source file is empty";
    public const string DuplicateSourcePath = "Source path '{0}' resolves to the same path as '{1}'";
    public const string DuplicateSchema = "Schema '{0}' is declared more than once";
    public const string MissingReferences = "Schema references could not be resolved: {0}";
    public const string InvalidJson = "Invalid JSON: {0}";
    public const string EmptyJson = "JSON value expected";
    public const string TrailingJsonContent = "Unexpected content after the JSON value";
    public const string SchemaExpected = "Avro schema expected";
    public const string ProtocolExpected = "Avro protocol expected";
    public const string MissingRootSchema = "Named schema or protocol required";
    public const string MissingSchemaProperty = "Required property '{0}' is missing";
    public const string InvalidSchemaName = "Property 'name' must be a non-empty string containing a valid Avro name, optionally prefixed with its namespace";
    public const string InvalidProtocolName = "Property 'protocol' must be a non-empty string containing a valid Avro name, optionally prefixed with its namespace";
    public const string InvalidFieldName = "Field property 'name' must be a non-empty string containing a valid Avro name";
    public const string InvalidRequestParameterName = "Request parameter property 'name' must be a non-empty string containing a valid Avro name";
    public const string InvalidNamespace = "Property 'namespace' must be a string containing a valid Avro namespace, or null";
    public const string InvalidSchemaType = "Property 'type' must be a non-empty string naming an Avro type or referencing a named type";
    public const string InvalidFieldType = "Field property 'type' must be a primitive type name, a named type reference, an inline type definition, or a union";
    public const string InvalidParameterType = "Request parameter property 'type' must be a primitive type name, a named type reference, an inline type definition, or a union";
    public const string InvalidFields = "Property 'fields' must be an array of field objects";
    public const string InvalidItems = "Property 'items' must be a primitive type name, a named type reference, an inline type definition, or a union";
    public const string InvalidValues = "Property 'values' must be a primitive type name, a named type reference, an inline type definition, or a union";
    public const string InvalidSymbols = "Property 'symbols' must be an array of strings containing valid Avro names";
    public const string InvalidAliases = "Property 'aliases' must be an array of non-empty strings, or null";
    public const string InvalidDoc = "Property 'doc' must be a string or null";
    public const string InvalidLogicalType = "Property 'logicalType' must be a non-empty string";
    public const string InvalidTypes = "Property 'types' must be an array of record, error, enum, or fixed definitions";
    public const string InvalidMessages = "Property 'messages' must be an object whose values are message objects";
    public const string InvalidRequest = "Property 'request' must be an array of request parameter objects";
    public const string InvalidResponse = "Property 'response' must be a primitive type name, a named type reference, an inline type definition, or a union";
    public const string InvalidErrors = "Property 'errors' must be null or an array of primitive type names, named type references, inline type definitions, or unions";
    public const string InvalidOneWay = "Property 'one-way' must be a boolean or null";
    public const string InvalidEnumDefault = "Enum property 'default' must be a string or null";
    public const string InvalidProtocolDeclarationType = "Protocol type declaration property 'type' must be 'record', 'error', 'enum', or 'fixed'";
    public const string InvalidSchemaReference = "Invalid type reference '{0}'; expected a name such as 'Order' or 'com.example.Order'";
    public const string InvalidFixedSize = "Property 'size' must be a positive 32-bit integer";
    public const string RecursiveSchemaDefinition = "Recursive schema definition detected for '{0}'.";
    public const string InvalidOneWayMessage = "One-way message '{0}' must have a null response and no declared errors";
    public const string InvalidCharacter = "Unexpected character '{0}'";
    public const string InvalidEscapeSequence = "Invalid escape sequence '{0}'";
    public const string InvalidNumber = "Invalid number literal '{0}'";
    public const string UnterminatedDocumentation = "Unterminated documentation comment";
    public const string UnterminatedComment = "Unterminated block comment";
    public const string UnterminatedString = "Unterminated string literal";
    public const string UnterminatedVerbatimIdentifier = "Unterminated verbatim identifier";
    public const string UnexpectedToken = "'{0}' expected";
    public const string UnexpectedJsonValue = "JSON value expected";
    public const string MisplacedAnnotation = "Annotation '@{0}' is not permitted on {1}";
    public const string MisplacedDocumentation = "Documentation comment is not permitted on {0}";
    public const string InvalidIdlDocument = "IDL document must contain a main schema directive or exactly one protocol declaration";
    public const string InvalidIdlDeclaration = "Protocol declarations are not permitted in a schema document";
    public const string InvalidIdlNamespace = "Annotation '@namespace' must have a string value";
    public const string InvalidIdlAliases = "Annotation '@aliases' must have an array of strings as its value";
    public const string InvalidIdlLogicalTypeAnnotation = "Annotation '@logicalType' must have a string value";
    public const string InvalidIdlOrder = "Annotation '@order' must have a string value";
    public const string InvalidIdlEnumDefault = "Enum default must be a string or null";
    public const string InvalidIdlFixedSize = "Fixed size must be a positive 32-bit integer";
    public const string InvalidIdlDecimalPrecision = "Decimal precision must be a 32-bit integer";
    public const string InvalidIdlDecimalScale = "Decimal scale must be a 32-bit integer";
    public const string ImportCycle = "Import cycle: {0}";
    public const string InvalidImportFileExtension = "Import '{0}' requires a '{1}' file; '{2}' has an incompatible extension";
    public const string MissingImport = "Import file '{0}' was not supplied as an AdditionalFile";
    public const string InvalidImportTarget = "Import '{0}' does not contain a valid {1}";
    public const string UnusedImport = "Import '{0}' is unused";
    public const string NoAvroLibraryDetected = "AvroSourceGeneratorAvroLibrary is 'Auto', but no supported Avro library was found";
    public const string MultipleAvroLibrariesDetected = "Multiple Avro libraries are referenced: {0}; set AvroSourceGeneratorAvroLibrary to 'Apache' or 'Chr'";

    public static string Get(AvroDiagnosticCode code) => code switch
    {
        AvroDiagnosticCode.None => None,
        AvroDiagnosticCode.UnsupportedSourceType => UnsupportedSourceType,
        AvroDiagnosticCode.EmptySource => EmptySource,
        AvroDiagnosticCode.DuplicateSourcePath => DuplicateSourcePath,
        AvroDiagnosticCode.DuplicateSchema => DuplicateSchema,
        AvroDiagnosticCode.MissingReferences => MissingReferences,
        AvroDiagnosticCode.InvalidJson => InvalidJson,
        AvroDiagnosticCode.EmptyJson => EmptyJson,
        AvroDiagnosticCode.TrailingJsonContent => TrailingJsonContent,
        AvroDiagnosticCode.SchemaExpected => SchemaExpected,
        AvroDiagnosticCode.ProtocolExpected => ProtocolExpected,
        AvroDiagnosticCode.MissingRootSchema => MissingRootSchema,
        AvroDiagnosticCode.MissingSchemaProperty => MissingSchemaProperty,
        AvroDiagnosticCode.InvalidSchemaName => InvalidSchemaName,
        AvroDiagnosticCode.InvalidProtocolName => InvalidProtocolName,
        AvroDiagnosticCode.InvalidFieldName => InvalidFieldName,
        AvroDiagnosticCode.InvalidRequestParameterName => InvalidRequestParameterName,
        AvroDiagnosticCode.InvalidNamespace => InvalidNamespace,
        AvroDiagnosticCode.InvalidSchemaType => InvalidSchemaType,
        AvroDiagnosticCode.InvalidFieldType => InvalidFieldType,
        AvroDiagnosticCode.InvalidParameterType => InvalidParameterType,
        AvroDiagnosticCode.InvalidFields => InvalidFields,
        AvroDiagnosticCode.InvalidItems => InvalidItems,
        AvroDiagnosticCode.InvalidValues => InvalidValues,
        AvroDiagnosticCode.InvalidSymbols => InvalidSymbols,
        AvroDiagnosticCode.InvalidAliases => InvalidAliases,
        AvroDiagnosticCode.InvalidDoc => InvalidDoc,
        AvroDiagnosticCode.InvalidLogicalType => InvalidLogicalType,
        AvroDiagnosticCode.InvalidTypes => InvalidTypes,
        AvroDiagnosticCode.InvalidMessages => InvalidMessages,
        AvroDiagnosticCode.InvalidRequest => InvalidRequest,
        AvroDiagnosticCode.InvalidResponse => InvalidResponse,
        AvroDiagnosticCode.InvalidErrors => InvalidErrors,
        AvroDiagnosticCode.InvalidOneWay => InvalidOneWay,
        AvroDiagnosticCode.InvalidEnumDefault => InvalidEnumDefault,
        AvroDiagnosticCode.InvalidProtocolDeclarationType => InvalidProtocolDeclarationType,
        AvroDiagnosticCode.InvalidSchemaReference => InvalidSchemaReference,
        AvroDiagnosticCode.InvalidFixedSize => InvalidFixedSize,
        AvroDiagnosticCode.RecursiveSchemaDefinition => RecursiveSchemaDefinition,
        AvroDiagnosticCode.InvalidOneWayMessage => InvalidOneWayMessage,
        AvroDiagnosticCode.InvalidCharacter => InvalidCharacter,
        AvroDiagnosticCode.InvalidEscapeSequence => InvalidEscapeSequence,
        AvroDiagnosticCode.InvalidNumber => InvalidNumber,
        AvroDiagnosticCode.UnterminatedDocumentation => UnterminatedDocumentation,
        AvroDiagnosticCode.UnterminatedComment => UnterminatedComment,
        AvroDiagnosticCode.UnterminatedString => UnterminatedString,
        AvroDiagnosticCode.UnterminatedVerbatimIdentifier => UnterminatedVerbatimIdentifier,
        AvroDiagnosticCode.UnexpectedToken => UnexpectedToken,
        AvroDiagnosticCode.UnexpectedJsonValue => UnexpectedJsonValue,
        AvroDiagnosticCode.MisplacedAnnotation => MisplacedAnnotation,
        AvroDiagnosticCode.MisplacedDocumentation => MisplacedDocumentation,
        AvroDiagnosticCode.InvalidIdlDocument => InvalidIdlDocument,
        AvroDiagnosticCode.InvalidIdlDeclaration => InvalidIdlDeclaration,
        AvroDiagnosticCode.InvalidIdlNamespace => InvalidIdlNamespace,
        AvroDiagnosticCode.InvalidIdlAliases => InvalidIdlAliases,
        AvroDiagnosticCode.InvalidIdlLogicalTypeAnnotation => InvalidIdlLogicalTypeAnnotation,
        AvroDiagnosticCode.InvalidIdlOrder => InvalidIdlOrder,
        AvroDiagnosticCode.InvalidIdlEnumDefault => InvalidIdlEnumDefault,
        AvroDiagnosticCode.InvalidIdlFixedSize => InvalidIdlFixedSize,
        AvroDiagnosticCode.InvalidIdlDecimalPrecision => InvalidIdlDecimalPrecision,
        AvroDiagnosticCode.InvalidIdlDecimalScale => InvalidIdlDecimalScale,
        AvroDiagnosticCode.InvalidIdlOneWayMessage => InvalidOneWayMessage,
        AvroDiagnosticCode.ImportCycle => ImportCycle,
        AvroDiagnosticCode.InvalidImportFileExtension => InvalidImportFileExtension,
        AvroDiagnosticCode.MissingImport => MissingImport,
        AvroDiagnosticCode.InvalidImportTarget => InvalidImportTarget,
        AvroDiagnosticCode.UnusedImport => UnusedImport,
        AvroDiagnosticCode.NoAvroLibraryDetected => NoAvroLibraryDetected,
        AvroDiagnosticCode.MultipleAvroLibrariesDetected => MultipleAvroLibrariesDetected,
        _ => throw new ArgumentOutOfRangeException(nameof(code), code, null)
    };
}
