<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Apache.Avro" />
  </ItemGroup>

  <!--Required since we're referencing the generator through the csproj instead of the package -->
  <Import Project="..\..\AvroSourceGenerator.props" />

  <ItemGroup>
    <AdditionalFiles Include="*.avdl" />
    <AdditionalFiles Include="*.avsc" />
  </ItemGroup>

  <ItemGroup>
    <Using Remove="System.Transactions" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\AvroSourceGenerator\AvroSourceGenerator.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
  </ItemGroup>

</Project>
