<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <LangVersion>preview</LangVersion>
    <UseMicrosoftTestingPlatformRunner>true</UseMicrosoftTestingPlatformRunner>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="xunit.runner.json" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Apache.Avro" />
    <PackageReference Include="Confluent.SchemaRegistry.Serdes.Avro" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="Microsoft.Testing.Extensions.GitHubActionsReport" PrivateAssets="all" />
    <PackageReference Include="Testcontainers" />
    <PackageReference Include="xunit.v3" />
    <PackageReference Include="xunit.runner.visualstudio">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\AvroSourceGenerator\AvroSourceGenerator.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
    <ProjectReference Include="..\AvroSourceGenerator.SmokeTests\AvroSourceGenerator.SmokeTests.csproj" />
  </ItemGroup>

  <Import Project="..\..\AvroSourceGenerator.props" />

  <ItemGroup>
    <AdditionalFiles Include="..\Schemas\*.avdl" CopyToOutputDirectory="PreserveNewest" Link="Schemas\%(Filename)%(Extension)" />
    <AdditionalFiles Include="..\Schemas\*.avsc" CopyToOutputDirectory="PreserveNewest" Link="Schemas\%(Filename)%(Extension)" />
    <AdditionalFiles Include="..\Schemas\*.avpr" CopyToOutputDirectory="PreserveNewest" Link="Schemas\%(Filename)%(Extension)" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="..\Serialization\Common\**\*.cs" Exclude="..\Serialization\Common\**\*ModelTests.cs;..\Serialization\Common\**\*SerializationTests.cs" Link="Serialization\%(Filename)%(Extension)" />
    <Compile Include="..\Serialization\Apache\**\*.cs" Link="Serialization\%(Filename)%(Extension)" />
    <Compile Include="..\Serialization\TaggedUnions\**\*.cs" Link="Serialization\%(Filename)%(Extension)" />
    <ProjectReference Include="..\AvroSourceGenerator.IntegrationTests\AvroSourceGenerator.IntegrationTests.csproj" />
  </ItemGroup>

</Project>
